- app/background/createWindow.js
- app/lib/config.js
- app/main.development.js
- app/main/createWindow.js
- app/main/createWindow/AppTray.js
- app/main/createWindow/buildMenu.js
For whatever reason <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> or <kbd>F12</kbd> etc does not open dev tools on windows.  Added a (development only) context menu to enable this.
> Added development context menu

- app/main/plugins/core/apps/index.js
- package.json
- test/plugins/apps/index.spec.js
* Two apps with same name, but different paths now will be displayed
* Update cerebro-tools
Fix for #52
> Apps search fix

- package.json
Do not require to use npm, it allows to use yarn.
Allow to use node 6
> Change dev engines

- app/main/createWindow.js
Open links from previews in default browser instead of navigating in cerebro web view 
Fix for #68
> Open links from previews in default browser

- app/main/containers/Search/index.js
- app/main/plugins/core/cerebro/settings/Settings/Hotkey/index.js
- app/main/plugins/core/files/index.js
- app/main/plugins/core/osx-apps/index.js
- docs/plugins/plugin-structure.md
* Copy to clipboard by ctrl+c
* Reveal by ctrl+r
* Do not show MacOS key symbols on linux and windows 
Fix for #61 and #37
> Hotkeys on windows and linux

- app/main/plugins/core/translate/Preview/index.js
- app/main/plugins/core/translate/constants.js
List of added languages:
* French
* Dutch
* Persian
* Ukrainian
* Catalan
* Chinese
* Arab
* Belarusian
* Hungarian
* Vietnamese
* Danish
* Hebrew
* Yiddish
* Indonesian
* Irish
* Icelandic
* Kazakh
* Kyrgyz
* Korean
* Latvian
* Lithuanian
* Norwegian
* Polish
* Portuguese
* Romanian
* Slovak
* Slovenian
* Thai
* Turkish
* Finnish
* Hindi
* Czech
* Swedish
* Estonian
* Esperanto
* Japanese
Fix #64
> Support more languages in translate plugin

- .gitignore
- app/lib/getWindowPosition.js
- app/main/containers/Search/index.js
- app/main/createWindow.js
I'll start with a demonstration of how the positioning and sizing actually works today on my box:
* Initially Cerebro window is small and centered
* Start typing and window expands over the boundary of my screen
* Hit Enter to run the selected app
* Next time I open Cerebro, the window is large
* Type and remove a character makes window small again, but not centered
* Next time I open Cerebro, the window is again small and centered
It is easy to fix the incorrectly large size on startup, but what to do with window expanding over the boundary of my screen when I start typing something...
I've got two basic ideas:
* Place the Cerebro window not in the center, but closer to the top of the screen. That way, there's a bit more available space for the window to grow.
* Always maintain Cerebro …
> Improve window position and size

- app/main/containers/Search/index.js
Fix #90 "Error: Attempting to call a function in a renderer window that has been closed or released." after the main window reload.
@maximbaz we forgot about it in your PR
> Fix js error popup

- README.md
Apple's operating system is called macOS, this PR fixed the name in the README file.
P.S. It has never been named OSx, it used to be OS X (pronounced O S 10).
> Fix macOS name

- app/main/components/ResultsList/Row/styles.css
- app/main/components/ResultsList/index.js
- app/main/components/ResultsList/styles.css
- app/main/constants/ui.js
> Hide empty preview and use all width for results in this case

- app/lib/plugins/npm.js
- app/package.json
- package.json
Using `tar.gz` is unpredictable: sometimes it doesn't unarchive some files without raising an error. In this case plugin shown as installed, but it doesn't work, because not all files are included. 
This approach after some tests feels more stable
> Use more stable approach for unarchiving plugins

- app/main/plugins/core/converter/currency/constants.js
I added some keys to `currency/constants.js` to support the Indian rupee.
One problem I ran into, is that synonyms work for the plain text values `rs` and `rupee*`, but not for the currency symbol `₹`. Typing e.g. <kbd>47 ₹</kbd> or <kbd>21 $ in ₹</kbd> doesn't do anything. Any ideas?
> Add Indian rupee

- app/main/createWindow.js
A small bug fix, steps to reproduce:
- Open cerebro, move the window somewhere and hide it
- Switch to chrome, enter full screen
- Hit the hotkey to open cerebro (you don't see it, but it is opened behind the chrome)
- Hit the hotkey again to close cerebro
- Exit from the chrome full screen
- Hit the hotkey to open cerebro again
Expected: the position is the same as where you moved it on the first step.
Actual: the position is lost, the window is centered.
Update: according to #39 it might be Linux related, or even window manager related issue.
> Save window position only when it's visible

- README.md
Hello @KELiON,
First, thank you very much for Cerebro! It's an incredible piece of software (clean code and easy to extend 👏👏👏).
This PR aims to add the DuckDuckGo plugin as a search engine to Cerebro's README file.
> Add DuckDuckGo plugin to Readme.md

- app/lib/trackEvent.js
Cerebro should work when something goes wrong in `node-machine-id`
Fix for #174 and #124
> Do not raise global exception if machine-id is not found

- app/main/createWindow.js
Small change to fix an issue where the Cerebro window would open behind Mac full screen apps or in a different Space.
> Display Above Fullscreen Apps

- app/main/plugins/core/cerebro/plugins/getAvailablePlugins.js
Hi @KELiON,
I noticed some of the newly developed plugins for Cerebro weren't available ASAP on its plugin search. I dug down the codebase and Github issues to see if someone had had this issue before, and found #79.
Based on #79, I've searched around for an official NPM registry search docs. It seems they've recently developed an API for their registry and properly documented: https://github.com/npm/registry/blob/956a880ec395d10ccc717e78c0a4fd56cf9356a4/docs/REGISTRY-API.md. As you can see, its docs date Jan 26.
This PR introduces a quick change on how Cerebro search for its plugins. Instead of using `npms.io`, it now uses the official npm registry, searching for the same `cerebro-plugin` keyword.
> Use NPM’s registry to search for plugins

- app/main/plugins/core/cerebro/settings/Settings/styles.css
@Razzile pointed out in #155 that the Settings plugin was using `Helvetica Neue` as the `font-family`, which isn't installed by default on operating systems other than macOS. I removed the declaration so that it falls back to `system-font-css` and picks up the OS default.
This works on elementary OS, but need someone to check if things are fine on macOS and Windows as well.
> Remove overriding font-family declaration in Settings

- app/main/createWindow.js
On mac you can close main window with cmd+w (or alt+f4 on windows). Previously it caused an error when you use cerebro shortcut next
Fix for #46
> Quit application when main window is closed

- .travis.yml
- app/lib/plugins/npm.js
- app/yarn.lock
- appveyor.yml
- package.json
On windows and Linux `os.tmpdir()` could be not empty, so we should create subdirectory for extracted package
> Fix plugin installation

- app/main/plugins/core/cerebro/plugins/index.js
So I took a crack at fixing #200.
This is what it looks like 
Platform specific categories can be added too.
Any reservations about the way it was implemented? The functional style was a bit difficult to adjust to, but it's good.
Fixes #200
> Split plugins into categories

- app/main/plugins/externalPlugins.js
#217 is caused by a race condition, when the `pluginsWatcher.on('addDir'` fires earlier than a folder is fully moved from the temporary directory to the `plugins/node_modules` during the plugin installation.
This is an ugly fix, that just waits one second before attempting to load the plugin, assuming that one second would be enough to move the files.
> Race condition: allow a second before trying to load the plugin

- docs/plugins/cerebro-tools.md
Hi, I've noticed a typo in the sample code when trying to create a plugin. This fixes it.
Thank you for your work!
> Fix typo in require memoizee

- app/main/components/KeyboardNav/index.js
- app/main/components/KeyboardNavItem/index.js
- app/main/containers/Search/index.js
Implement [lightweight vim-mode](https://github.com/KELiON/cerebro/issues/170#issuecomment-286065838). Now you can use <kbd>cmd/ctrl+hjklo</kbd> for navigation instead of arrows and enter
Partially implement #170
> Implement lightweight vim mode

- .eslintignore
- app/background/background.js
- app/main/main.js
- webpack.config.development.js
Electron doesn't inherit the `$PATH` defined in dotfiles (.bashrc/.bash_profile/.zshrc/etc), so we should fix it for plugins
> Call fix-path

- app/lib/getFileIcon/windows.js
- app/main/plugins/core/basic-apps/index.js
- app/main/plugins/core/basic-apps/windows.js
- app/package.json
Removed win-icon-extractor and switched to electrons getFileIcon, which works the same way without additional dependencies.
Also fixed linux icons support.
> Switch to electrons getFileIcon on windows

- package.json
- yarn.lock
Fixes npm install breaking on nslog since the new version no longer depends on nslog.
Ref: https://github.com/electron/electron-rebuild/issues/124
> Update electron-rebuild to version 1.5.7

- app/main/plugins/core/basic-apps/linux.js
It works, while not perfect yet.
Ideally there should be support for search priorities. When match is found in app name - it should be higher that when it is found in binary name.
Technically implementation is similar to Windows.
> [Linux] Add binary name support during app search

- docs/plugins/examples.md
- docs/plugins/plugin-structure.md
Finish last part of #230. Does this need to be more detailed?
> Add settings docs

- app/main/plugins/core/basic-apps/Preview.js
Switch to SmartIcon instead of img in application preview. This should fix #274.
> Switch to SmartIcon in basic apps preview

- app/main/plugins/core/basic-apps/index.js
Especially on Linux, it is very common to have multiple `*.desktop` files for the same application, 2 examples:
```
...
{ description: 'View current processes and monitor system state',
exec: 'gnome-system-monitor',
filename: 'gnome-system-monitor-kde.desktop',
hidden: false,
icon: '/usr/share/app-install/icons/utilities-system-monitor.svg',
id: 'gnome-system-monitor-kde.desktop',
name: 'GNOME System Monitor',
path: '/usr/share/applications/gnome-system-monitor-kde.desktop' },
{ description: 'View current processes and monitor system state',
exec: 'gnome-system-monitor',
filename: 'gnome-system-monitor.desktop',
hidden: false,
icon: '/usr/share/app-install/icons/utilities-system-monitor.svg',
id: 'gnome-system-monitor.desktop',
name: 'System Monitor',
path: …
```
> Only show unique binaries in search results

- app/main/plugins/externalPlugins.js
It allows to use plugins without extra configuration and es2015 syntax for export/import. So, now plugin can do `export default { fn }` and it will work without `add-module-exports` babel plugin
> Allow to use plugins with `default` key

- app/main/plugins/externalPlugins.js
Watching full plugin path to file doesn't work because file is not updated by web pack, but delete and added back
> Fix plugin updates watcher

- app/lib/rpc/functions/initializePlugins.js
run initializeAsync for plugins only after 2 seconds when main render…er process is loaded
> Ugly hack for main renderer/background race condition in plugin initialization

- app/main/createWindow.js
- app/main/createWindow/toggleWindow.js
Now it doesn't depend on way we hide the window
> Always restore focus in previous app on Mac

- app/lib/config.js
Added --portable switch based on the feature in TagSpaces to save app data in the install directory, allowing portable usage on USB drives.
https://github.com/tagspaces/tagspaces
> support for portable mode

- app/main/components/Cerebro/index.js
hiding electron window after `openExternal` leaves focus in cerebro application, instead of launched app. So, launching application after hiding cerebro window fixes it.
Fixing #369
> Activate launched applications

- package.json
Fixes #363 and #352 
The category field needed to be set to a registered value defined by the [freedesktop.org spec](https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html#category-registry)
Of all the given options 'Utility'  seemed like the best fit for cerebro.
This will fix the desktop file validation issue and also adds cerebro to the dash menu in Ubuntu
> Fix desktop file validation bug in Ubuntu

- app/plugins/externalPlugins.js
When plugin had `initialize`, but not `initializeAsync`, first method wasn't called
> Fix plugin initialisation

- app/plugins/core/plugins/Preview/index.js
- app/plugins/core/plugins/getDebuggingPlugins.js
- app/plugins/core/plugins/index.js
- app/plugins/core/plugins/loadPlugins.js
Resolving #376.
Now plugins, that are currently in development (`yarn start` from create-cerebro-plugin is working in plugin directory) are shown in separate section. It could be useful for development plugins with settings:
> Added section for "Development" plugins

- app/main/createWindow/toggleWindow.js
Fix for #405, only tested on Windows.
This only works for production environment, because of a check in `cerebro\app\main\createWindow.js` (line 60).
> Restore focus to previous window on blur/hide (production only)

- app/background/background.js
- app/lib/initializePlugins.js
- app/lib/plugins/settings/get.js
- app/lib/plugins/settings/index.js
- app/main/actions/search.js
- test/actions/search.spec.js
Make `settings` object available on initialize(Async) like so:
```
const initialize = (settings) => {
console.log(settings)
}
```
and
```
const initializeAsync = (cb, settings) => {
console.log(settings)
}
```
Still allows backwards compatibility:
`const initialize = () => { }` and `const initializeAsync = (cb) => { }` should still work
> Pass 'settings' object to plugins on initalize() and initializeAsync()

- README.md
When I started Using this Application I was a bit confused about how I can change the theme as I wasn't able to find any Documentation about it so, I added this PR.
> feat: update README.md how to change Themes

- .eslintrc.json
Hello, maintainers. Thank you for the nice app.
It is not a critical fix, but .eslintrc without extension is deprecated ([https://eslint.org/docs/user-guide/configuring#configuration-file-formats](https://eslint.org/docs/user-guide/configuring#configuration-file-formats))
Add .json extension to .eslintrc
> Add extension to .eslintrc

- app/lib/getWindowPosition.js
- app/main/createWindow.js
This PR aims to fix #131.
Instead of using the "Default" display to open Cerebro, it will use the "current" display, based on the cursor position on the screen.
The main functionality is working, but you still see for brief moments, the Cerebro window opened in the previous screen, before appearing on the new screen. A little bit annoying but not a big deal for me.
I also noticed, sometimes I need to press the Hotkey 2 times before Cerebro opens. Not sure if its related with any of the changes I made.
This PR was only tested on Linux but it uses standard Electron functions, so it should work fine elsewhere.
> feat: Open cerebro window on Active screen

- app/main/components/Cerebro/index.js
Fixes plugins not being able to call `event.preventDefault()` with the desired effect
> fix: Move event handling to before the 'preventedDefault' property is read

- app/main/css/themes/dark.css
- app/main/css/themes/light.css
Some linux distributions that do not use a desktop environment do
not define a system font. On these systems, the system-font css file
does not work if none of the font families are matched (and it
seems chrome ignores it anyway).
I added sans-serif as a fallback font, which is usually always defined
in fontconfig as a sans-serif font.
Without this, cerebro uses an ugly ans obscure serif font due to
no fallback having been found.
> Fix serif font on systems that do not define a system font

- app/lib/config.js
- app/main/createWindow.js
On some tiling window managers, simply moving the mouse outside the cerebro window
blurs it (and closes it), which gets very frustrating. This adds a configuration option to disable
this behavior.
The default value keeps the current behavior.
> Add config option to hide on blur

- app/main/createWindow.js
- app/plugins/core/settings/Settings/index.js
When i use this application, i found i can not use partial function in some plugins, for example: i cannot use preview in cerebro-google plugin because i come from china and if i want to use the google api like 'http://suggestqueries.google.com/complete/search?client=firefox&q=${query}', i need set a proxy like socks proxy.But there is not a place in cerebro settings to set proxy, and this problem also confuse others, so i did this. 
The ProxyRule can refer to this doc 
https://www.electronjs.org/docs/api/session#sessetproxyconfig
> feat: add proxy in cerebro settings

- README.md
- app/main/createWindow/autoStart.js
- package.json
This PR disables the autostart option when running the app in development mode (not includes the development option in the production app, just `yarn dev`).
Autostart was causing an electron popup window on start because it fails while trying to start an executable that doesn't exist, as the app isn't compiled. More info [here](https://stackoverflow.com/a/60780958)
To delete de entry in the start options of the PC users can run Cerebro with `yarn dev` and edit the settings disabling (and now also enablig) the option. This will clear the entry and the window won't show again. Autostart is now never activated on development mode.
fix #573
> fix: disable autostart when running `yarn dev`

- .github/workflows/pr.yml
- README.md
- __mocks__/@electron/remote.js
- __mocks__/plugins.js
- app/package.json
- package.json
> fix: fix mock files and release settings

- app/main/components/Cerebro/index.js
> fix: clipboard issues

- app/main/createWindow/AppTray.js
- docs/plugins/plugin-structure.md
Added:
- `ctrl+shift+i` for developer tools in main window
- `ctrl+shift+b` for developer tools in background window
(`ctrl+shift+i` is the shortcut for opening dev tools in chrome so this should be easy to remind)
fix #358
> feature: developer tools shortcut

- app/main.development.js
- app/plugins/core/version/index.js
- docs/plugins/plugin-structure.md
> chore: add cerebro version to `process.env`

- __mocks__/@electron/remote.js
- __mocks__/electron.js
- app/background/background.js
- app/lib/__tests__/loadThemes.spec.js
- app/lib/config.js
- app/lib/initPlugin.js
- app/lib/initializePlugins.js
- app/lib/plugins/settings/__tests__/get.spec.js
- app/lib/plugins/settings/__tests__/validate.spec.js
- app/lib/plugins/settings/get.js
- app/lib/plugins/settings/get.spec.js
- app/main/actions/__tests__/search.spec.js
- app/main/actions/__tests__/statusBar.spec.js
- app/main/actions/search.js
- app/plugins/core/index.js
- app/plugins/externalPlugins.js
- jest.config.js
> test: add more unit tests

- app/background/background.js
- app/main/main.js
- app/package.json
- app/yarn.lock
With the update of the packages it seems to be no longer necessary to use this fix-path. I removed it and everything worked normally, I think we can go on without it and if we find any unforeseen, maybe develop native.
> feat: remove fix-path dependencies

- app/background/index.html
Finally found that the problem was a bug wth the encoding.
By just adding meta charset to the background, the app is now working.
fix #599
> fix: add encoding to background renderer

- package.json
- yarn.lock
Latest version of @cerebroapp/cerebro-ui is broken. With this rollback we get the previous version so cerebro continues working while solve the issue with this dep.
re #615 re #614 re #607
> fix: rollback cerebro-ui dep

- README.md
- Fixed grammar to sound more natural, some misspelled words, missing words, and some missing commas. (english grammar nerd stuff)
- added `yarn --force` mentioned in https://github.com/cerebroapp/cerebro/issues/552#issuecomment-1249302400 because otherwise you get:
```
yarn run v1.22.19
$ yarn build && npx electron-builder
$ run-p build-main build-renderer
/bin/sh: run-p: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
> Update the grammar in the README + add command in build from source process

- app/plugins/core/plugins/blacklist.js
- app/plugins/core/plugins/getDebuggingPlugins.js
- app/plugins/core/plugins/initializeAsync.js
We will be using the new version of the package when installing plugins for the first time in Mac.
Done:
- Added `@cerebroapp/cerebro-mac-apps` to the default plugins list
- Blacklisted `cerebro-mac-apps` to avoid plugin duplicates
- Removed an unnecessary console.log statement
> chore: move to `@cerebroapp/cerebro-mac-apps`

- app/plugins/core/plugins/Preview/FormItem.js
- app/plugins/core/plugins/Preview/Settings.js
Fixes #626 
The main problem was that
```
config.set('plugins', {
...config.get('plugins'),
[name]: values,
})
```
was called before the value of `values` was updated.
Solution: moved it to useEffect with the dependency of `values`.
Furthermore, the dropdown settings weren't rendered correctly as the `Select` Component expects one of the `options` as its value (like `{ label: 'string', value: 'string' }`) and not just a string. So when a string option is used, find the corresponding option.
> fix: Fix plugin settings

- app/main/components/Cerebro/index.js
`cmd+a` was working on Windows as it is a native command on Windows (works out of the box).
Now this command should be available in all platforms.
NOTE: There is a lot of work to do to improve `Cerebro` component. Migrating to newer React versions will allow us to use the `event.code` instead of `event.keyCode` that is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and is also less readable than `event.code`
```js
event.code === "KeyC" // We know is char C
event.keyCode === 67 // We can't know what char it is
```
fix #628
> feat: Select current text with `cmd+a`

- app/lib/config.js
- app/main/components/Cerebro/index.js
- app/plugins/core/settings/Settings/index.js
Added a new option to automatically select the input on show.
This is really util for users who also use the option to keep the input when closing Cerebro.
fix #164
> feat: select main input on show option

- app/background/background.js
- app/main.development.js
- app/main/createWindow/AppTray.js
- app/main/main.js
- app/plugins/core/reload/index.js
We were reloading only the two renderer processes. This was causing the main process to continue subscribed to older renderers that were not existing.
```bash
(node:22748) MaxListenersExceededWarning: Possible EventEmitter memory leak detected.
11 render-view-deleted listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
```
Now when using the `reload` command, both the main process and the renderer processes will be reloaded. This makes Cerebro to reload a bit slower but avoids memory leaks.
> fix: memory leak on reloading

- app/lib/plugins/npm.js
- app/package.json
- app/yarn.lock
Seems like we were using the wrong dep for moving folders. As we can read in https://github.com/sindresorhus/move-file/issues/7, `move-file` was designed for moving **files** (not _folders_). With this fix we implement `fs-extra` to handle this and also for removing dirs.
fix #636
> fix: use correct dependency to move/delete folders

- app/background/background.js
- app/background/index.html
- app/lib/initializePlugins.js
- app/main/actions/search.js
- app/plugins/core/autocomplete/index.js
- app/plugins/core/plugins/Preview/index.js
- app/plugins/core/plugins/getInstalledPlugins.js
- app/plugins/core/plugins/loadPlugins.js
- app/plugins/externalPlugins.js
- app/plugins/index.js
This PR should make Cerebro more performant.
The idea of the double renderer process was to make the second take care of the heavier tasks.
However, it was doing too much work by duplicating tasks that are already done in the main renderer.
The loading of plugins and the control over the addition of new plugins was being done in both renderers, which led to an unnecessary waste of resources (duplicated chockidar instances watching folders, double loading of plugins)
With this PR, we make the second renderer do what it is supposed to do: take care of the async loads of plugins
ref #118
> feat(plugins): improve plugins load

- app/main.development.js
When displaying the main window for Cerebro so far the primary screen has been chosen. This is inconvenient for workstations with more than 1 screen. After this commit is applied the main window will be displayed in the screen containing the mouse pointer (or the screen closest to the pointer if the pointer is in between screens).
fix cerebroapp/cerebro#647
> feat(main window): display main window on the screen containing or closest to the mouse pointer

- app/lib/config.js
- app/main/components/Cerebro/index.js
- app/plugins/core/settings/Settings/index.js
Now in Cerebro Config there's a new text field to customize the placeholder text on the searchbar. By default it's always "Cerebro search"
fix #672
> feat(cerebro): added customization option for placeholder text on search bar
