cerebroapp/cerebro

- package.json
> Update node-machine-id package

- app/lib/getAbbr.js
- app/main/plugins/core/basic-apps/linux.js
- app/main/plugins/core/basic-apps/windows.js
- app/main/plugins/core/osx-apps/index.js
- test/plugins/osx-apps/index.spec.js
Search apps by abbreviation, i.. 
*   League of Legends -> lol
*   AudioBookBinder -> abb
Implemented #65
> Search apps by abbreviation

- app/lib/config.js
- app/main/containers/Search/index.js
- app/main/createWindow.js
- app/main/plugins/core/cerebro/settings/Settings/index.js
When it is false we show previous state of window
In other case we show empty input without results
Implement idea from #44
> Added flag `clean on hide` to settings

- app/main/plugins/core/converter/currency/constants.js
I was missing ukrainian currency, this is a simple patch that adds it to the converter.
> Currency converter: add ukrainian currency

- README.md
* Sort plugins list alphabetically;
* Added devdocs plugin
> Add devdocs plugin

- app/main/createWindow/AppTray.js
> Fix changing "developer mode" checkbox when tray icon is hidden

- README.md
I just got this up to a decent point. Can you take a look? Any pointers would be welcome
> Add new stackoverflow plugin

- README.md
Accorgind to 
https://github.com/KELiON/cerebro/blob/603cb555eaeb4d1db73adab9b1bbf95911c07c65/app/lib/config.js#L9
and 
https://github.com/electron/electron/blob/v1.1.0/docs/api/app.md#appgetpathname
> Add config file path to readme

- app/main/containers/Search/index.js
Just use system binginds for that shortcut
Fix for #143
> Do not clean search input by cmd/ctrl+backspace, 

- README.md
@KELiON I created a plugin for searching information on GitHub, do give it a look
> Add github plugin

- README.md
HI @KELiON 👋 
Awesome work on Cerebro. I hacked together an NPM search plugin last night and figured you might want to add it to the list 🙂
> Add NPM Plugin to the Readme

- README.md
Kill won't work at all for windows, and is partially broken on linux boxes.
> Move kill to macOS plugins.

- README.md
Signed-off-by: Mat Munn <mat@matmunn.me>
> Added plugin to Readme

- README.md
> Move plugins list to Cerebro's Awesome List

- README.md
Added official gitter channel from #43 to Readme
> Added gitter chat to readme

- .babelrc
- yarn.lock
It causes two issues: something is broken in google → searchFn is not a function
Another issue: settings -> after change it is not updated (with react issue in setState)
> Revert babel presets config

- app/main/plugins/core/cerebro/index.js
- app/main/plugins/core/cerebro/reload/index.js
> Add reload plugin

- app/main/createWindow.js
Issue: https://github.com/KELiON/cerebro/issues/229
Solution: https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback
> Single Instance Application

- app/main/plugins/core/cerebro/index.js
- app/main/plugins/core/cerebro/version/index.js
Add aliases like `cfg`, `params` & `config` for `settings` command.
> Add `version` command

- app/lib/config.js
- app/main/createWindow.js
- app/main/createWindow/AppTray.js
- app/main/createWindow/donateDialog.js
- app/package.json
- package.json
- yarn.lock
* Added donate dialog
* Update electron to version 1.6.2
> Added donate dialog + update electron

- app/main/components/Form/Button.js
- app/main/components/Form/index.js
- app/main/components/Form/styles.css
- app/main/plugins/core/translate/Preview/index.js
- app/main/plugins/core/translate/Preview/styles.css
Added a button on view of the translate plugin to swap languages quickly
> Swap languages on translate plugin

- app/plugins/core/settings/Settings/Hotkey.js
> Fix hotkey binding input

- package.json
Needed to guarantee that it uses uglify-es instead of old uglify-js
Fix #356
> Fix path to uglifyjs binary

- app/lib/config.js
- app/lib/trackEvent.js
- app/main.development.js
- app/plugins/core/settings/Settings/index.js
> add opt-in for statistics reporting

- app/main/createWindow/AppTray.js
See https://github.com/KELiON/cerebro/issues/404
> Change input upon selecting 'settings' from taskbar

- app/plugins/core/plugins/index.js
> Fix cerebro fail when no description provided for published plugin

- app/main/index.html
Fixed the link tag in file /app/main/index.html to match W3C convention as mentioned here:
https://www.w3.org/TR/2011/WD-html5-author-20110705/the-link-element.html
> Fix the link tag to match W3C convention

- docs/plugins/examples.md
A small correction in Docs/Plugins/Examples :)
> [Docs] Fix code block

- README.md
Closes #220 
This pr changes the readme added to information on how to install plugin manually.
> feat: add install plugins manually

- app/background/createWindow.js
- app/lib/getWindowPosition.js
- app/main.development.js
- app/main/createWindow.js
- package.json
- yarn.lock
> chore: update electron to 12.0.5

- .commitlintrc.json
- .husky/commit-msg
- README.md
- package.json
- yarn.lock
> chore: implement conventional commit standard

- app/plugins/core/plugins/blacklist.js
- app/plugins/core/plugins/loadPlugins.js
> feat(plugins): plugins blacklist

- electron-builder.json
- package.json
- Extracted electron-build configuration from package.json to make it simpler
- Updated author to reflect cerebro organization
- Fixed a typo in the description
> build(electron-builder): extract build configuration from package.json

- app/package.json
> CI: add email to build options

- app/package.json
- package.json
Once we have merged #604 we can merge this and generate a new release.
> chore(release): bump version to 0.8.0

- .github/workflows/build.yml
- package.json
- yarn.lock
- Updated `@cerebropap/cerebro-ui` to last version
- Added macos-latest to the build CI (as it seems that Cerebro is working well in MacOS)
fix #607 #614 #615
Special thanks to @chflick for his contribution in https://github.com/cerebroapp/cerebro-ui/pull/10
> fix(cerebro-ui): update broken cerebro-ui dep
